### ISSUE TITLE
Bot doesn't register votes without spaces between good/bad and bot

### ISSUE THREAD

**Issue by HadManySons** [woodske/GoodBot_BadBot#10]
The bot should also recognize when people have said "GoodBot" and "BadBot" as well as with spaces

**Comment by HadManySons** [comment]
Created a pull request to fix this issue.

**Comment by woodske** [comment]
Thanks, I'll look it over today and merge it if it looks good.

**Comment by HadManySons** [comment]
I'm not well versed in JavaScript, so I left it to where you can edit it if I made a logic or syntax error or something.

**Comment by woodske** [comment]
Sorry I didn't get around to this. If you want to make a new pull request and make the edits I'll merge it.
