### ISSUE TITLE
Your Avoid5 post has no-good fifthglyphs in it!

### ISSUE THREAD

**Issue by willowiscool** [woodske/GoodBot_BadBot#13]
Avoid5 is a community all about avoiding that awful fifth glyph of our glyph list. In [your post](https://www.reddit.com/r/AVoid5/comments/6vcbg2/did_you_watch_that_solar_blotting/dlzi7sa/) you had many fifth-glyphs, and it was so awful I had to lay down for a bit. Pls fix.

**Comment by woodske** [comment]
I am asham{}d.
