### ISSUE TITLE
[Suggestion] Sort worst bots by 1 - *upper* bound of score confidence interval

### ISSUE THREAD

**Issue by frei0** [woodske/GoodBot_BadBot#14]
This will display bots that are more confidently known to be hated, and give a list of bots people have actually heard of and agree are bad.

It will be more symmetrical to the way best bots are calculated (no "minimum votes" parameter to tweak)

This is also mathematically equivalent to sorting the lower bound of the score confidence, if you switched up/down votes (it may be easier to think about implementation this way). 

Preview of what this looks like (top 20 bad bots):
![screen shot 2017-08-30 at 10 45 53](https://user-images.githubusercontent.com/1476684/29886882-754931ba-8d70-11e7-8713-ad52b5d10a23.png)

May want to sweep these results for non-bots before posting.

I also suggest doing a sweep on these bad bots for deleted profiles, or encouraging reports for them

**Comment by frei0** [comment]
I edited the above, my excel screenshot had some errors in it

**Comment by woodske** [comment]
Yeah that look a lot better. Thanks!
