### ISSUE TITLE
Stats based on subreddit breadth

### ISSUE THREAD

**Issue by o11c** [woodske/GoodBot_BadBot#18]
Some of the top bots are very narrow in scope. What are the best bots that operate in many subreddits?

Additionally, for any given subreddit, what is the best bot counting only votes within that subreddit (ow, my indices)?

**Comment by woodske** [comment]
I haven't been collecting subreddit data, but I could run a script that looks at how many subreddits each bot has participated in.

I do agree that the rank should take into consideration the breadth of participation, but stats is not my strong suit, so if you have a suggestion on how to adjust the scores I'd love to hear it. 

I'm not sure what you mean by your second question.
