### ISSUE TITLE
Good Bot / Bad Bot upvotes

### ISSUE THREAD

**Issue by morgano86** [woodske/GoodBot_BadBot#23]
I quickly glossed over the code but it doesn’t appear to take into account upvotes of someone’s comment.

For example If one person replies “Good Bot” it doesn’t make sense for 100 other people to also reply “Good Bot” as it creates spam. Most people seem to upvote a single comment and if these aren’t accounted for then they should be.

Example: http://www.reddit.com/r/worldnews/comments/76oeji/276_killed_in_deadliest_single_attack_in_somalias/doful19

Forgive me if I missed it.

**Comment by morgano86** [comment]
I just noticed it doesn’t seem to account for variations such as “goodbot” or “badbot”?

**Comment by woodske** [comment]
The problem with counting upvotes is that there's no way to tell who is upvoting (that I know of). My intention was to collect unique votes which is why I did it based off of comments. That way I can see who voted for which bot and only count their vote once.

**Comment by morgano86** [comment]
But a user can only upvote a comment once anyway. And if a user wanted they could create fake accounts to write good bot / bad bot too. Unfortunately neither method is accurate but currently a lot of votes are unaccounted for and the current system leads to excessive spam.

My suggestion would be to utilise an algorithm that takes in to consideration the total number of upvotes and comments a thread has. Use this to apply an upper limit to the expected feedback (to stop malicious users from manipulating the voting). 

So for terms good bot / bad bot you can account for each individual user. For upvotes applied directly to comments you could apply a weighted decision.

So someone replying Good Bot which has 100 upvotes on a thread with 16,000 karma would be considered more natural than a thread with only 50 karma.

Using this you could then account for the additional voting. You could even take in to consideration the upvotes received by the bit directly. All would ensure a more accurate view and reduced spam.

I’ve also noticed some users write great bot and other positive or negative terms which could easily be accounted for with some additional search terms.

**Comment by morgano86** [comment]
You closed this without an explanation. Your system encourages spam by not taking into account users up-voting users who have already commented "Good Bot" or "Bad Bot". In fact the majority of votes seem to be registered this way and therefore your system of measurement is unreliable without taking in to account this method of voting.
