### ISSUE TITLE
Does your bot look for comments that only contain the phrase "Good bot" or "bad bot"?

### ISSUE THREAD

**Issue by SreenivasVRao** [woodske/GoodBot_BadBot#26]
`var comment = key.body.substring(0,8).toLowerCase();`

will look at only the first eight characters, correct?

'Oh wow, good bot' will not register a vote I think. https://www.reddit.com/r/Torontobluejays/comments/7umq38/february_means_baseball_is_back_hdmh/dtmxk7j/ -> for example.

**Comment by woodske** [comment]
Yeah, I wanted it to be an intentional vote. So if someone was just mentioning that there's a bot that looks for good bot, then it wouldn't count that. I know it ends up missing some, but it picks up enough. And there's a system in place so people can check if their votes counted.

**Comment by morgano86** [comment]
This is such a bad idea, hardly anyone sticks to the format you hard coded.
