### ISSUE TITLE
/u/SirBelvedere is not a bot

### ISSUE THREAD

**Issue by HellGate94** [woodske/GoodBot_BadBot#3]
or he is a next gen ai that infiltrated us and searches for weaknesses to destroy us all in the future. make your own decision but dont tell me i didnt warn you. but maybe he is just a normal user who knows. anyway he is an awesome guy that does patchnotes for dota 2 and is so fast that he is called bot as a joke

**Comment by woodske** [comment]
Haha if the good people say he's a bot, then so be it.

**Comment by HellGate94** [comment]
sounds good to me 😄
