### ISSUE TITLE
Worst bot calculation error

### ISSUE THREAD

**Issue by wasdennnoch** [woodske/GoodBot_BadBot#4]
![](https://i.imgur.com/y2YMuiJ.png)

The bot has 5 bad votes and 0 good votes. I don't know if you're dividing by zero but I have the feeling that the value shouldn't be 31855221172287180.

**Comment by woodske** [comment]
It's because it's taking the inverse. Not sure about the best way to fix it, but I'll increase the minimum vote count in the meantime.
