### ISSUE TITLE
Use a better domain

### ISSUE THREAD

**Issue by wasdennnoch** [woodske/GoodBot_BadBot#5]
Right now it seem you're using the default heroku subdomain; I don't have experience with heroku but they list a custom domain even under the free plan so it should be possible to use a better sounding and more descriptive domain (something with goodbotbadbot). There will also soon be a .bot TLD available, that would be nice too if it won't be too expensive ^^

**Comment by woodske** [comment]
I didn't know that was part of the free plan. Thanks for the heads up!

**Comment by wasdennnoch** [comment]
At least it says "custom domains".

If you want to be as cheap as possible on the domain as well you can register a .tk domain for free (or .ml, .ga, .cf, .gq); They don't sound as nice tough ^^

**Comment by WesCook** [comment]
Avoid .tk domains.  They're perceived as malware by many people and AV scanners.  As far as I know reddit doesn't even allow .tk links to be posted without moderator approval.

**Comment by woodske** [comment]
Changed the site name so it's but better.
