### ISSUE TITLE
SirBelvedere is not a bot

### ISSUE THREAD

**Issue by chetmichals** [woodske/GoodBot_BadBot#8]
I know he can seem like a bot due to him being quick as lightning, but he really is human.

**Comment by tejaskale** [comment]
Does this just consider any user that gets the reply "Good Bot" or "Bad Bot" as a bot?

**Comment by SharpOB** [comment]
Really begs the question of how shitty and pointless reddit bots are getting now.

**Comment by woodske** [comment]
I'm adding filtering probably on Tuesday and will purge the database on non bots. I have exams coming up so haven't had much time to work on it.
